# Generated by Django 5.1.1 on 2025-05-30 17:34

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rifa', '0002_alter_dolar_valor_bs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('precio_unidad', models.FloatField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('direccion', models.CharField(max_length=500)),
                ('foto', models.ImageField(upload_to='eventos/')),
                ('total_tickets', models.IntegerField()),
                ('minimo', models.IntegerField(default=0)),
                ('color_principal', models.CharField(max_length=50)),
                ('color_secundario', models.CharField(max_length=50)),
                ('color_oscuro', models.CharField(max_length=50)),
                ('color_texto', models.CharField(max_length=50)),
                ('color_hover', models.CharField(max_length=50)),
                ('color_fondo', models.CharField(max_length=50)),
                ('color_header', models.CharField(max_length=50)),
                ('hora_espera', models.CharField(max_length=50)),
                ('eliminar_tickets', models.BooleanField()),
                ('mostrar_ocupados', models.BooleanField()),
                ('permitir_eleccion', models.BooleanField()),
                ('permitir_parcial', models.BooleanField()),
                ('permitir_sin_comprobante', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=500)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('No verificado', 'No Verificado'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='No verificado', max_length=500)),
                ('metodo', models.IntegerField(choices=[(1, 'Bancolombia'), (2, 'Pago Movil'), (3, 'Binance')], null=True)),
                ('monto', models.FloatField(default=0)),
                ('dolar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rifa.dolar')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalComprobante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=500)),
                ('referencia', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('No verificado', 'No Verificado'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='No verificado', max_length=500)),
                ('metodo', models.IntegerField(choices=[(1, 'Bancolombia'), (2, 'Pago Movil'), (3, 'Binance')], null=True)),
                ('monto', models.FloatField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dolar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rifa.dolar')),
                ('evento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.evento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comprobante',
                'verbose_name_plural': 'historical comprobantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tickets', models.IntegerField()),
                ('precio', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='gestion.evento')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.comprobante')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento')),
            ],
            options={
                'indexes': [models.Index(fields=['numero'], name='gestion_num_numero_e235b5_idx')],
            },
        ),
    ]
