# Generated by Django 5.1.1 on 2025-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='cliente/')),
                ('ubicacion', models.CharField(max_length=255)),
                ('portada', models.ImageField(upload_to='cliente/')),
                ('tiktok', models.CharField(blank=True, max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=500)),
                ('youtube', models.CharField(blank=True, max_length=500)),
                ('instagram', models.CharField(blank=True, max_length=500)),
                ('linkedin', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
