# Generated by Django 5.1.1 on 2025-03-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.comprobante')),
            ],
            options={
                'indexes': [models.Index(fields=['numero'], name='gestion_num_numero_e235b5_idx')],
            },
        ),
    ]
