# Generated by Django 5.1.1 on 2025-03-02 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_comprobante_confirmado_and_more'),
        ('rifa', '0002_alter_dolar_valor_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='dolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rifa.dolar'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='metodo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='dolar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rifa.dolar'),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='metodo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
