# Generated by Django 5.1.1 on 2025-06-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='metodos/')),
                ('titular', models.CharField(max_length=300)),
                ('posicion', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('fecha_editado', models.DateField(auto_now=True)),
                ('titulo_1', models.CharField(blank=True, max_length=100)),
                ('contenido_1', models.CharField(blank=True, max_length=100)),
                ('titulo_2', models.CharField(blank=True, max_length=100)),
                ('contenido_2', models.CharField(blank=True, max_length=100)),
                ('titulo_3', models.CharField(blank=True, max_length=100)),
                ('contenido_3', models.CharField(blank=True, max_length=100)),
                ('nota', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='historicalcomprobante',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='foto',
            field=models.ImageField(upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='metodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion.metodopago'),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='metodo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.metodopago'),
        ),
    ]
