# Generated by Django 5.1.1 on 2025-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_metodopago_remove_comprobante_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nota',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
