# Generated by Django 5.1.1 on 2025-03-03 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_comprobante_dolar_comprobante_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='status',
            field=models.CharField(choices=[('No verificado', 'No Verificado'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='No verificado', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='status',
            field=models.CharField(choices=[('No verificado', 'No Verificado'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='No verificado', max_length=500),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
