# Generated by Django 5.1.1 on 2025-06-03 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_metodopago_remove_comprobante_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nota',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
