# Generated by Django 5.1.1 on 2025-06-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_comprobante_fecha_alter_comprobante_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='fecha_verificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
