# Generated by Django 5.1.1 on 2025-03-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_comprobante_status_historicalcomprobante_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('nombre', models.CharField(max_length=500)),
                ('foto', models.ImageField(upload_to='eventos/')),
                ('precio_unidad', models.FloatField()),
                ('total_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tickets', models.IntegerField()),
                ('precio', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento')),
            ],
        ),
    ]
