# Generated by Django 5.1.1 on 2025-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_comprobante_fecha_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
