# Generated by Django 5.1.1 on 2025-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_evento_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='minimo',
            field=models.IntegerField(default=0),
        ),
    ]
