# Generated by Django 5.1.1 on 2025-03-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_evento_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numerorifa',
            name='fecha',
        ),
        migrations.AddField(
            model_name='numerorifa',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento'),
        ),
    ]
