# Generated by Django 5.1.1 on 2025-06-06 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_comprobante_nota_historicalcomprobante_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='fecha_creado',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
