# Generated by Django 5.1.1 on 2025-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_comprobante_fecha_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
