# Generated by Django 5.1.1 on 2025-03-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_numerorifa_fecha_numerorifa_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='historicalcomprobante',
            name='confirmado',
        ),
    ]
