# Generated by Django 5.1.1 on 2025-03-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_comprobante_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento'),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='evento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.evento'),
        ),
    ]
