# Generated by Django 5.1.1 on 2025-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_evento_valor_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
