# Generated by Django 5.1.1 on 2025-06-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_comprobante_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor_dolar',
            field=models.FloatField(),
        ),
    ]
