# Generated by Django 5.1.1 on 2025-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_evento_valor_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='dolar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='dolar',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
