# Generated by Django 5.1.1 on 2025-04-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_visualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacion',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='gestion.evento'),
        ),
    ]
