# Generated by Django 5.1.1 on 2025-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_comprobante_dolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='referencia',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
