# Generated by Django 5.1.1 on 2025-05-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_visualizacion_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='historicalcomprobante',
            name='metodo',
        ),
    ]
