# Generated by Django 5.1.1 on 2025-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_comprobante_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='referencia',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
