# Generated by Django 5.1.1 on 2025-05-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_comprobante_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='metodo',
            field=models.IntegerField(choices=[(1, 'Bancolombia'), (2, 'Pago Movil'), (3, 'Binance')], null=True),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='metodo',
            field=models.IntegerField(choices=[(1, 'Bancolombia'), (2, 'Pago Movil'), (3, 'Binance')], null=True),
        ),
    ]
