# Generated by Django 5.1.1 on 2025-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_comprobante_metodo_historicalcomprobante_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcomprobante',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
