# Generated by Django 5.1.1 on 2025-06-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_comprobante_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcomprobante',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
