# Generated by Django 5.1.1 on 2025-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_comprobante_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='moneda',
            field=models.CharField(choices=[('$', 'Dolar'), ('€', 'Euro'), ('Bs', 'Bolivar')], default='$', max_length=10),
            preserve_default=False,
        ),
    ]
