# Generated by Django 5.1.1 on 2025-05-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_comprobante_monto_historicalcomprobante_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento'),
        ),
    ]
