# Generated by Django 5.1.1 on 2025-06-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_metodopago_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerorifa',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.comprobante'),
        ),
        migrations.AlterField(
            model_name='numerorifa',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.evento'),
        ),
    ]
