# Generated by Django 5.1.1 on 2025-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_numerorifa_comprobante_alter_numerorifa_evento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='evento_fechas_idx'),
        ),
    ]
