# Generated by Django 5.1.1 on 2025-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_evento_evento_fechas_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['banco'], name='metodopago_banco_idx'),
        ),
    ]
