# Generated by Django 5.1.1 on 2025-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_metodopago_metodopago_banco_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metodopago',
            name='metodopago_banco_idx',
        ),
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['posicion'], name='metodopago_banco_idx'),
        ),
    ]
