# Generated by Django 5.1.1 on 2025-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_metodopago_metodopago_banco_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metodopago',
            new_name='metodopago_posicion_idx',
            old_name='metodopago_banco_idx',
        ),
    ]
