# Generated by Django 5.1.1 on 2025-06-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_rename_metodopago_banco_idx_metodopago_posicion_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['telefono'], name='gestion_com_telefon_b51aa1_idx'),
        ),
    ]
