# Generated by Django 5.1.1 on 2025-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_comprobante_gestion_com_telefon_b51aa1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_peso',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
