# Generated by Django 5.1.1 on 2025-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolar',
            name='valor_bs',
            field=models.FloatField(),
        ),
    ]
